blank_issues_enabled: false
contact_links:
  - name: Regex Intelligence Exchange Documentation
    url: https://github.com/Infopercept/Regex-Intelligence-Exchange-by-Invinsense/blob/master/docs/README.md
    about: Check our documentation for help with installation, usage, and troubleshooting
  - name: Community Discussions
    url: https://github.com/Infopercept/Regex-Intelligence-Exchange-by-Invinsense/discussions
    about: Ask questions, share ideas, and connect with other Regex Intelligence Exchange users
  - name: Security Issues
    url: security@infopercept.com
    about: Report security vulnerabilities responsibly (do not use public issues)