name: Validate and Update Patterns

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Validate all patterns
        run: |
          python tools/validate-all-patterns.py

      - name: Update statistics and data files
        run: |
          python tools/update-all-data.py

      - name: Commit and push changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add PATTERNS_SUMMARY.md data/vendors.json data/products.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: Update pattern statistics and data files" && git push)